# --- Defaults ---
defaults:
  - _self_

project_name: TextConditionedVAE
seed: 42
data:
  train_dir: data/${env.name}/training
  cache_dir: null
  resolution: 112
  batch_size: 128
  num_workers: 4
  image_column: image
  caption_column: text
  text_encoder_path: openai/clip-vit-base-patch32
model:
  _target_: VAE.text_conditioned_vae.TextConditionedVAE
  n_downsample: 3
  encoder_n_res: 2
  input_dim: 3
  dim: 32
  norm: in
  activ: selu
  pad_type: replicate
  encoder_final_dim:
  - 7
  - 7
  latent_channel: 4
  output_dim: 3
  text_encoder: ${models.data.text_encoder_path}
  discriminator_fc_hidden:
  - 64
  - 128
training:
  num_epochs: 500
  seed: 42
  kl_weight: 1
  adv_lambda: 1.0
  adv_weight: 1.0
  logs: logs
  output_dir: model_weights/vae
  experiment_name: TextConditionedVAE
  log_media_interval: 8000
  log_values_and_images: false
  validation_prompts:
  - Agent is in a room surrounded by blue walls. Agent sees to the bottom left,
    a blue ball which is 2 units apart at (2,5).
  - Agent is in a room surrounded by blue walls. No other objects can be seen
  - Agent is in a room surrounded by grey walls. Agent sees to the bottom right,
    a yellow ball which is 2 units apart at (4,5).
  - Agent is in a room surrounded by grey walls. Agent sees to the bottom left,
    a yellow ball which is 2 units apart at (2,5) and to the bottom right, a green
    ball which is 2 units apart at (5,6).
  generate_interval: 8000
  num_images_to_generate: 10
  save_weight_freequency: 50
optimizer:
  lr: 0.0001
  betas:
  - 0.9
  - 0.999
  weight_decay: 0.01
  eps: 1.0e-08
accelerator:
  mixed_precision: 'no'
  gradient_accumulation_steps: 1
  log_with: wandb
  project_dir: ${models.training.logs}
  logging_dir: ${models.training.logs}/logs
test:
  model_dir: model_weights/TextConditionedVAE/2025-09-26_19-25-12_7W466E