# --- Defaults ---
defaults:
  - _self_

project_name: TextConditionedVAE
model_name : "VAE"
seed: 42
data:
  train_dir: data/${env.name}/training_images
  cache_dir: null
  batch_size: 64
  num_workers: 4
  image_column: image
  caption_column: text
  text_encoder_path: openai/clip-vit-base-patch32
model:
  _target_: VAE.text_conditioned_vae.TextConditionedVAE
  n_downsample: 4
  encoder_n_res: 3
  input_dim: 3
  dim: 32
  norm: ln
  activ: lrelu
  pad_type: replicate
  encoder_final_dim:
  - 5
  - 5
  latent_channel: 4
  text_encoder: ${models.data.text_encoder_path}
  discriminator_fc_hidden:
  - 32
  - 64
  - 128
  observation_mode : ${env.observation_mode}
  use_image_discriminator: true
  disc_params:
    base_channels: 64
    n_layers: 3
    norm: in
  use_weighted_recon: false
  use_mine: false           # Enables mutual information minimization
  is_perceptual_loss : true
training:
  num_epochs: 500
  seed: ${models.seed}
  kl_weight: 1.0
  adv_lambda: 1.0
  adv_weight: 5.0
  logs: logs
  output_dir: model_weights/vae
  experiment_name: ${models.project_name}
  log_media_interval: 8000
  log_values_and_images: True
  validation_prompts: ${env.validation_prompts}
  generate_interval: 8000
  num_images_to_generate: 10
  save_weight_freequency: 50
  img_adv_weight : 5.0
  img_adv_lambda : 1
  mine_weight: 1           # Weight for MINE loss term
  recon_mix_weight: 0.5
optimizer:
  lr: 0.0001
  betas:
  - 0.9
  - 0.999
  weight_decay: 0.01
  eps: 1.0e-08
  lr_mine : 0.00001
accelerator:
  mixed_precision: 'no'
  gradient_accumulation_steps: 1
  log_with: wandb
  project_dir: ${models.training.logs}
  logging_dir: ${models.training.logs}/logs
test:
  model_dir: model_weights/VAE/2025-10-28_18-06-08_QIBDOK/