# --- Defaults ---
defaults:
  - _self_

project_name: TextConditionedVAE
model_name : "VAE"
seed: null
data:
  train_dir: data/MiniWorld/agent
  cache_dir: null
  batch_size: 32
  num_workers: 8
  image_column: image
  caption_column: text
  text_encoder_path: openai/clip-vit-base-patch32 #openai/clip-vit-base-patch32
model:
  _target_: VAE.text_conditioned_vae.TextConditionedVAE
  n_downsample: 4
  encoder_n_res: 3
  input_dim: 3
  dim: 64
  norm: ln
  activ: lrelu
  pad_type: replicate
  encoder_final_dim:
  - 5
  - 5
  latent_channel: 8
  text_encoder: ${models.data.text_encoder_path}
  discriminator_fc_hidden:
  - 64
  - 128
  - 128
  observation_mode : ${env.observation_mode}
  disc_params:
    base_channels: 64
    n_layers: 3
    norm: in
  is_perceptual_loss : true
  use_image_discriminator : true
  use_mine: false           # Enables mutual information minimization
  use_ema: false
  use_coord_conv : false
  ema_decay: 0.999
  max_grad_norm: 1.0
  max_sequence_length: 110
training:
  num_epochs: 500
  seed: ${models.seed}
  kl_weight: 1.5
  kl_annealing:
    enable: true
    start: 1.0
    stop: ${models.training.kl_weight}
    n_cycles: 1
    ratio: 0.5
  adv_lambda: 1.0
  adv_weight: 15.0
  logs: logs
  output_dir: model_weights/vae
  experiment_name: ${models.project_name}
  log_media_interval: 8000
  log_values_and_images: False
  validation_prompts: ${env.validation_prompts}
  generate_interval: 8000
  num_images_to_generate : 10
  save_weight_freequency : 50
  img_adv_weight : 10.0
  img_adv_lambda : 1
  mine_weight: 1           # Weight for MINE loss term
  critic_updates: 2        # Number of discriminator updates per generator update
  recon_mix_weight: 0.5
  is_model_fine_tune : false
optimizer:
  lr: 0.0002
  betas:
  - 0.9
  - 0.999
  weight_decay: 0.01
  eps: 1.0e-08
  lr_mine : 0.00001
  scheduler:
    type: cosine
    T_max: ${models.training.num_epochs}
    eta_min: 0.000001
accelerator:
  mixed_precision: 'no'
  gradient_accumulation_steps: 1
  log_with: wandb
  project_dir: ${models.training.logs}
  logging_dir: ${models.training.logs}/logs
test:
  model_dir: model_weights/VAE/MiniWorld/2025-12-30_13-01-53_NT0L29/VAE.tar