# --- Defaults ---
defaults:
  - _self_

project_name: TextConditionedVAE
seed: 42
data:
  train_dir: data/${env.name}/training_images
  cache_dir: null
  batch_size: 64
  num_workers: 4
  image_column: image
  caption_column: text
  text_encoder_path: openai/clip-vit-base-patch32
model:
  _target_: VAE.text_conditioned_vae.TextConditionedVAE
  n_downsample: 3
  encoder_n_res: 3
  input_dim: 3
  dim: 32
  norm: in
  activ: gelu
  pad_type: replicate
  encoder_final_dim:
  - 7
  - 7
  latent_channel: 4
  output_dim: 3
  text_encoder: ${models.data.text_encoder_path}
  discriminator_fc_hidden:
  - 32
  - 64
  - 128
  observation_mode : images
  use_image_discriminator: false
  disc_params:
    base_channels: 64
    n_layers: 3
    norm: in
training:
  num_epochs: 500
  seed: 42
  kl_weight: 1
  adv_lambda: 1.0
  adv_weight: 5.0
  logs: logs
  output_dir: model_weights/vae
  experiment_name: TextConditionedVAE
  log_media_interval: 8000
  log_values_and_images: false
  validation_prompts: ${env.validation_prompts}
  generate_interval: 8000
  num_images_to_generate: 10
  save_weight_freequency: 50
  img_adv_weight : 1
  img_adv_lambda : 1
optimizer:
  lr: 0.0001
  betas:
  - 0.9
  - 0.999
  weight_decay: 0.01
  eps: 1.0e-08
accelerator:
  mixed_precision: 'no'
  gradient_accumulation_steps: 1
  log_with: wandb
  project_dir: ${models.training.logs}
  logging_dir: ${models.training.logs}/logs
test:
  model_dir: model_weights/TextConditionedVAE/2025-10-11_14-10-51_C4JS5A/