defaults:
  - _self_

project_name: TextConditionedVAE
model_name : "DARLA"
# --- Data Configuration ---
data:
  train_dir: data/${env.name}/Random/vae
  image_column: "image"
  cache_dir: null
  resolution: 112
  batch_size: 64
  num_workers: 8 
  caption_column: text
  text_encoder_path: openai/clip-vit-base-patch32

# --- VAE Model Architecture ---
model:
  _target_: VAE.vae.VAE
  in_channels: 3
  out_channels: 3
  down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D"]
  up_block_types: ["UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D"]
  block_out_channels: [64, 128, 256]
  layers_per_block: 1
  latent_channels: 4
  norm_num_groups: 32

# --- Training Hyperparameters ---
training:
  num_epochs: 50 # Increased for more realistic training
  seed: null
  kl_weight: 1
  logs : "logs"
  output_dir: "model_weights/vae"
  experiment_name: "VAE"
  log_media_interval: 8000 # Log images every N steps
  log_values_and_images: True
  generate_interval : 8000
  num_images_to_generate : 8
  save_weight_freequency: 50

# --- Optimizer Configuration (AdamW) ---
optimizer:
  lr: 1e-4 # A slightly higher learning rate can work well for VAEs
  betas: [0.9, 0.999]
  weight_decay: 1e-2
  eps: 1e-8

# --- Accelerator Configuration ---
accelerator:
  mixed_precision: 'no' # Can be 'no', 'fp16', or 'bf16'
  gradient_accumulation_steps: 1
  log_with: "wandb" # or "tensorboard", "comet_ml"
  project_dir: ${models.training.logs}
  logging_dir: ${models.training.logs}/logs