# @package agent
_target_: baselines.successor_feature.agent.sf_simple.SFSimpleAgent
name: sf_simple
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-3
lr_task: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
hidden_dim: 1024
feature_dim: 128
stddev_schedule: 0.2
stddev_clip: 0.3
sf_dim: 128
update_task_every_step: 2
nstep: 3
batch_size: 256
init_critic: true
num_init_steps: 4096 # set to ${num_train_frames} to disable finetune policy parameters
update_encoder: ${update_encoder}
normalize_basis_features: true
normalize_task_params: true