name : MiniWorld 
objects : [["box", "ball"]]
reward_objects : [["box"]]
layout : ["grass/concrete"] #options:wood/brick_wall, grass/concrete
max_steps : 100  
render_mode : "none"
size : 10
obs_width : 80
obs_height : 80
n_downsample : 3
total_timestep : 200000
fps : 2.5
verbose : True
observation_mode : image
mission : ???
validation_prompts :
  - The room features gray walls, a green floor, and a blue sky ceiling with a blue Box centered on the floor.
  - An empty room with a bright blue sky ceiling, tall gray walls, and a flat green grass floor.
  - A simple room with gray walls, a green floor, and a blue sky ceiling containing a single blue cube.
  - A simple room with gray walls, a blue sky ceiling, a green grass floor, and a green ball positioned in the front-left corner.
  - A green Box sits on a green floor with gray sloped walls and a blue sky overhead.
  - A simple outdoor scene featuring a clear blue sky, a large gray sloped hill or wall, and a flat green grassy floor with no interactable objects present.
  - The room features gray walls, a green grass floor, and a blue sky background with a blue Box on the floor.
  - A simple 3D room with gray walls, a green floor, and a blue sky ceiling contains a large green Ball positioned to the left and a blue Box to the right.