name : SimplePickup
# data_collection_allowed_types : [[1,1], [1,0]] # [[0,1], [1,0], [4,0], [5,1]], [[2,0], [3,0], [3,1]], [[2,1]]
# agent_training_allowed_types : [[2,0], [3,0], [3,1]]
# test_allowed_types : [[2,1]]
objects : [["green ball", "red ball"]]
reward_objects : [["red ball"]]
wall_color : ["grey"]
tile_size : 8
max_steps : 50
agent_view_size : 7
render_mode : "none"
size : 9
highlight : false
n_downsample : 3
total_timestep : 1000000
fps : 2.5
verbose : True
observation_mode : image
mission : ???
validation_prompts :
  - Agent is in a room surrounded by grey walls. Agent sees to the bottom left,
    a blue ball which is 2 units apart at (2,5).
  - Agent is in a room surrounded by grey walls. No other objects can be seen
  - Agent is in a room surrounded by grey walls. Agent sees to the bottom right,
    a green ball which is 2 units apart at (4,5).
  - Agent is in a room surrounded by grey walls. Agent sees to the bottom left,
    a green ball which is 2 units apart at (2,5) and to the bottom right, a red
    ball which is 2 units apart at (5,6).