defaults:
  - env: MiniWorld # Default environment

training:
  model_name: "openai/clip-vit-base-patch32"
  batch_size: 256
  num_epochs: 10
  learning_rate: 2e-5
  output_dir: "model_weights/finetuned_clip/${env.name}"
  
data:
  # The data path is choosen depending upon the env selected
  caption_file: "data/${env.name}/agent/metadata.jsonl" 

wandb:
  use_wandb: true
  project: "TextConditionedVAE"
  name: "finetune_clip_${env.name}"