
defaults:
  - env: MiniWorld
  - models@models.vae: vae
  - _self_

models:
  model_name: "diffusion"
  test:
    model_dir: "model_weights/diffusion/MiniWorld/2026-01-02_00-37-48_XAJI0Y/checkpoint-468000" 
  
  # For get_dataloader compatibility
  model:
    observation_mode: ${env.observation_mode}
    max_sequence_length: 77
  
  data:
    train_dir: data/MiniWorld/agent
    cache_dir: null
    batch_size: 32
    num_workers: 8
    image_column: image
    caption_column: text
    text_encoder_path: openai/clip-vit-base-patch32

  accelerator:
    project_dir: "logs/diffusion"
    logging_dir: "logs/diffusion"
    gradient_accumulation_steps: 1
    mixed_precision: "fp16"
    log_with: "wandb"
    
  training:
    seed: 42
    experiment_name: "diffusion_imagination_v1"
    num_epochs: 100
    logs: "logs/diffusion"
    save_interval: 50000
    num_train_timesteps: 1000
    num_inference_steps: 50
    save_top_k: 3
    log_media_interval: 8000
    num_images_to_generate: 4
    uncond_prob: 0.1
    imagination_strength: 0.75
    
  optimizer:
    lr: 1e-4
    beta1: 0.9
    beta2: 0.999
    weight_decay: 1e-2
    eps: 1e-8
    scheduler:
      type: "cosine"
      warmup_steps: 500

save_path: "model_weights/"

env:
  name: "MiniWorld"

